services:
  whispertrace-api:
    image: whispertrace-api-base
    mem_limit: 1024m
    build:
      context: ../../../
      dockerfile: ./whispertrace-deployment/docker/image/whispertrace-api/Dockerfile.base
    ports:
      - ${WHISPERTRACE_API_PORT:-5001}:5000
