FROM python:3.11-slim AS whispertrace-api-base

RUN apt-get update && \
    apt-get install -y python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip && \
    pip3 install pipenv

COPY ./whispertrace-api/ /whispertrace-api

ENV HOME=/whispertrace-api
WORKDIR /whispertrace-api

RUN pipenv install --deploy --ignore-pipfile

WORKDIR /whispertrace-api/src

EXPOSE 5000

CMD [ "echo", "Hello from the whispertrace-api-base container." ]